### ISSUE TITLE
Support for Alpha Level Format

### ISSUE THREAD

**Issue by TheEeveeLovers** [GoldenTadpole/Mapee#4]
Could you add support for the Alpha Level Format used from Infdev to Beta 1.2_02? I am having trouble finding software to map it and this software seems like a potential candidate as it seems to already be planned (despite the last commit being a year old).

**Comment by GoldenTadpole** [comment]
Yes. I am rewriting it in C++ and Alpha support will be added. You'll have to wait a few months though.

**Comment by TheEeveeLovers** [comment]
I now understand why there's been a big inactivity
Converting one programming language to another is quite the task, moreso with bigger codebases
- You have to consider syntax differences (luckily C# is somewhat similar to C++ in this way so it's not as much as an issue), and if you have lots of dependencies on external 3rd party libraries (which it seems Mapee has little of), they may not be available in the new language meaning you have to find alternatives _(which is another rabbit hole of missing features I won't explain here)_.
- Also, differences between the standard functions in each language, using C# and C++ as an example, where in C# you would use `Console.WriteLine("foo");` in C++ you would use `cout << "foo" << endl;` (assuming when you included `<iostream>` you also did `using namespace std;` which is normal for starter projects)

There's very likely more examples, but this is just the gist of it
